### ISSUE TITLE
 show ip nbar version active

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/genieparser#394]
I missing the parser for `show ip nbar version active`

**Comment by danielgraziano** [comment]
Hi @urskog84 this is correct, we do not have this parser developed. We encourage the community to develop and contribute apis/parsers/etc. If you are willing to do this we have a guide that explains how to here.

How to write a parser: https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

Contribution Guidelines: https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/contribute/contribute.html

**Comment by urskog84** [comment]
No Problem @danielgraziano, i will add the parser my self. 

Hmm, insetting when i looking true the source code. I can see that you have update the structure of the tests. putting the return object and the cli_output in separate files..

**Comment by urskog84** [comment]
i have open pull request now!

https://github.com/CiscoTestAutomation/genieparser/pull/403

**Comment by c-m-a** [comment]
Hi @danielgraziano, how do I know which parsers are missing?

**Comment by c-m-a** [comment]
what about this command? It gives a XML output!

```sh
showip nbar protocol-pack active taxonomy
```

**Comment by danielgraziano** [comment]
@urskog84 I see you have the pull request open now so I will close this issue as we can track it there. Thanks again!

@c-m-a  you can see all of the available parsers here: https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers
Since I am closing this issue, if you have more questions about contributing, please email pyats-support-ext@cisco.com
