### ISSUE TITLE
Is this project dead???

### ISSUE THREAD

**Issue by bskine** [CiscoTestAutomation/genieparser#611]
Haven't seen any pushes for a long time... Is this project dead??  Is windows support on the road map?

**Comment by ThomasJRyan** [comment]
Hello there,

This project is very much not dead and is in constant active development. The reason you see few commits is because we do most of the development internally at Cisco and then release that internal code out to the world after putting it through sanitization checks. 

What contributions you see on this repository were made by external users unrelated to Cisco. 

As for whether we have plans to support Windows or not, the answer to that would be no. We are only supporting Unix-based systems and have no plans to support Windows going forward.
