### ISSUE TITLE
Models and keys seem to have no clear structure across all modules

### ISSUE THREAD

**Issue by empusas** [CiscoTestAutomation/genieparser#624]
While working with the genie parser I noticed that I need to write a different parser for the output of every genie parser to normalize the data.
For example the MAC address key is sometimes "mac_address", "mac_addr" or simply "mac".
Also the structure from parsed output of the commands about the inventory items seems to be different from every parser module.

Looking at the models from Cisco it is stated that the  MAC address would have  the key "mac_address" for IOS, IOS-XE and NX-OS devices.
https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/_models/interface.pdf

Would it not make sense to adhere to the same keys and structure for the other platforms as well? Just add platform specific ones and omit the ones that are not applicable.

I would have expected that the genieparser provides a unified output across platform at least for the common values.
If I request for example interface information, why not provide the same output regardless if the device is from Cisco or any other vendor?

**Comment by tahigash** [comment]
@empusas 

This might be one of misunderstanding on pyATS parsers. whenever we can, we try to have same key name across platforms in parser schema. but it's not always true and sometimes hard to manage to be agnostic between platforms especially from contributor's perspective. (usually, the contributor care only one platform)

So, pyATS offers unified(agnostic) way via:

1) use Genie Conf for configuration and Genie Ops for operational state (instead of Genie Parser)
2) use APIs. APIs argument should be same and what API returns should be same across platforms as well. 

if you need to handle different platforms in agnostic way, please consider above instead of genie parser directly. of course, you can use genie parser on your own, but you will need to take care of difference and have logic to absorb/abstract the difference.

**Comment by tahigash** [comment]
not an issue. closing this issue. please feel free to reopen if something needs to be discussed/checked.
