### ISSUE TITLE
show_crypto parser remote id

### ISSUE THREAD

**Issue by ciesinsn** [CiscoTestAutomation/genieparser#718]
show crypto ikev2 sa detail

https://github.com/CiscoTestAutomation/genieparser/blob/f6050e4d9f9a7da73221f49d225578d9d87b8a78/src/genie/libs/parser/iosxe/show_crypto.py#L1471

        # Remote id: 22.1.1.2
        r8 = "^Remote id: +(?P<remote_id>[\d\.]+)$"
        p8 = re.compile(r8)

A remote id does not have to be a IP address.  For instance when using FlexVPN and setting a remote identity the remote id shown on the far side will be a name, not IP.  The regex should be changed to allow more than just IP addresses.

**Comment by Taarini** [comment]
Hi 

Thanks for reporting. 

Would you like to contribute for the genieparser repository by creating a PR.
Please follow the below link on how it has to be done, https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html

As genieparser is community driven, we request you to create a PR and we can assist you in the process of approval from our team.

**Comment by Taarini** [comment]
Hi

Did you get a chance to look at it and contribute to the community

**Comment by Taarini** [comment]
Hi 

If there isn't any response this issue is going to be closed tomorrow

**Comment by ciesinsn** [comment]
So I report a issue. You ask if I could fix it and submit my own PR on this issue and when I don't respond you decide to just close the issue like it didn't ever exist if I don't fix it. That makes great sense. 

I get this is a community supported tool but maybe I don't feel comfortable enough correcting this issue myself as I've never submitted parser changes to this project and am just starting to navigate creating my own parser from the documentation.  I struggled a bit in figuring out that process and only finally think I figured it out.  I can only assume modifying a existing parser is a similar process but as I mentioned I am not sure as I've never done it before.

**Comment by Taarini** [comment]
We are working on multiple tickets based on the impact and priority, despite that we are following up with all our users so that we can resolve the issues as a community. After multiple follow ups and delay in response we had to take next set of actions. I hope now it makes sense.

We are still here to help based on your timely response. Please let us know, If you are planning to work on this fix so that I can help you through the process.

If you are not ready to contribute we can add this to our backlog based on our existing priorities, but you are required to share the device output of the parser command so that we can proceed in our end.

Please do not delay your response.

**Comment by ciesinsn** [comment]
I will attempt to contribute a fix to this.  I will let you know if I have any questions on the process.

**Comment by Taarini** [comment]
The PR is merged. Thanks for your contribution.
