### ISSUE TITLE
show mac address-table not caching all MACs

### ISSUE THREAD

**Issue by leoanez** [CiscoTestAutomation/genieparser#93]
Hi,

The parser of show mac address-table is ignoring MAC Addresses learned from an interface configured with Service Instances. Here is a sample of the output:

  vlan   mac address     type    learn     age              ports
------+----------------+--------+-----+----------+--------------------------
* 888  0100.5e00.02d7    static  Yes          -   Router
* 999  7848.59e9.0bcc   dynamic  Yes          0   Gi7/19 
   **777  c4ea.1dae.afb0   dynamic  Yes        205   Gi8/6 efp_id 30**

First two MAC Addresses are part of the output dictionary, 3rd one is ignored due to the **efp_id 30** at the end.

**Comment by xiaoxinz-cisco** [comment]
Hello @leoanez ,

Since I'm not sure which OS you're using with, I tested your output in IOSXE. Maybe you're using a different OS, but the concepts behind the fix are same. 

In [iosxe/show_fdp.py#L76](https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/iosxe/show_fdb.py#L76):

`        p4 = re.compile(r'^(?P<entry>[\w\*] )?\s*(?P<vlan>All|[\d\-]+) +(?P<mac>[\w.]+)'
                                    ' +(?P<entry_type>\w+) +(?P<learn>\w+) +(?P<age>[\d\-\~]+) '
                                    '+(?P<intfs>(vPC )?[\w\/\,\-\(\)]+)$')`, 

which supports
- 888 0100.5e00.02d7 static Yes - Router
- 999 7848.59e9.0bcc dynamic Yes 0 Gi7/19

In the current regex, grouped key `intfs` does not support cases with space `\s`.

Once add `\s` in the last group, it will support the last output:
- 777 c4ea.1dae.afb0 dynamic Yes 205 Gi8/6 efp_id 30

`        p4 = re.compile(r'^(?P<entry>[\w\*] )?\s*(?P<vlan>All|[\d\-]+) +(?P<mac>[\w.]+)'
                                    ' +(?P<entry_type>\w+) +(?P<learn>\w+) +(?P<age>[\d\-\~]+) '
                                    '+(?P<intfs>(vPC )?[\w\/\,\-\(\)\s]+)$')`, 



[regex101](https://regex101.com/) is a nice website where you can try the regular expression on 👍 
I prepared two screenshots for you, but I'm able to paste it in the comment, could you please try it on your own and create a pull request for it? It would be faster than waiting for our release! 

We appreciate your contribution.

Thanks,
Irene

**Comment by leoanez** [comment]
Hi Irene,

I just tested your solution and its working. Going to create the pull request.

Thank you.
Leo
